#ifndef PROTOBLOCKCORE_GLOBAL_H
#define PROTOBLOCKCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOBLOCKCORE_LIBRARY)
#  define PROTOBLOCKCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOBLOCKCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOBLOCKCORE_GLOBAL_H
